name: Build and Publish z64lib

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: build-z64lib
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Cache pip
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Upgrade pip and install build deps
      run: |
        python -m pip install --upgrade pip build

    - name: Build Wheel and Tarball
      run: python3 -m build

    - name: store-dist
      uses: actions/upload-artifact@v5
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: publish-z64lib
    if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'pre')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/z64lib
    permissions:
      id-token: write

    steps:
    - name: Download dist
      uses: actions/download-artifact@v5
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish dist
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}

