class AseqArg:
    def __init__(self, value: int):
        self.value = value

class ArgU8(AseqArg): ...
class ArgS8(AseqArg): ...
class ArgU16(AseqArg): ...
class ArgS16(AseqArg): ...
class ArgVar(AseqArg): ...